name: make vs

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install -y python3-pip

    - name: install j2cli
      run: pip3 install --user j2cli

    - name: Run check
      run: make init

    - name: Run distcheck
      run: make configure PLATFORM=vs
      
    - name: Run distcheck
      run: make SONIC_BUILD_JOBS=4 all
      
